import 'package:new_app/domain/admin/answer_maintain/maintain_answer_repository.dart';
import 'package:new_app/domain/admin/candidates_list/candidate_list_repository.dart';
import 'package:new_app/domain/admin/employees_list/employee_list_repository.dart';
import 'package:new_app/domain/admin/metric_maintain/maintain_metric_repository.dart';
import 'package:new_app/domain/admin/metrics_list/metrics_list_repository.dart';
import 'package:new_app/domain/admin/question_maintain/maintain_question_repository.dart';
import 'package:new_app/domain/admin/test_link_generation/test_link_generation_repository.dart';
import 'package:new_app/domain/admin/test_maintain/maintain_test_repository.dart';
import 'package:new_app/domain/admin/tests_list/test_list_repository.dart';
import 'package:uuid/uuid.dart';

final MaintainAnswerRepository maintainAnswerRepository;
final CandidateListRepository candidateListRepository;
final EmployeeListRepository employeeListRepository;
final MaintainMetricRepository maintainMetricRepository;
final MetricListRepository metricListRepository;
final MaintainQuestionRepository maintainQuestionRepository;
final TestLinkGenerationRepository testLinkGenerationRepository;
final MaintainTestRepository maintainTestRepository;
final TestListRepository testListRepository;
String newId() => const Uuid().v4();
